// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3P3NZnRtGM7ng06rrGDceONOQh0PHMZ4',
    appId: '1:615185650546:web:a911254683ddad07b0c3eb',
    messagingSenderId: '615185650546',
    projectId: 'chatly-5bc63',
    authDomain: 'chatly-5bc63.firebaseapp.com',
    storageBucket: 'chatly-5bc63.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSj8teT9r9ZfhBL7C4qAsirZX1QazUWc',
    appId: '1:615185650546:android:81a21c5ae9dce7bfb0c3eb',
    messagingSenderId: '615185650546',
    projectId: 'chatly-5bc63',
    storageBucket: 'chatly-5bc63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0xLiVvuCFT-RsBEA1dT8vl9LNwPt8meo',
    appId: '1:615185650546:ios:141ecd13e34cb6a1b0c3eb',
    messagingSenderId: '615185650546',
    projectId: 'chatly-5bc63',
    storageBucket: 'chatly-5bc63.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0xLiVvuCFT-RsBEA1dT8vl9LNwPt8meo',
    appId: '1:615185650546:ios:141ecd13e34cb6a1b0c3eb',
    messagingSenderId: '615185650546',
    projectId: 'chatly-5bc63',
    storageBucket: 'chatly-5bc63.firebasestorage.app',
    iosBundleId: 'com.example.chatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3P3NZnRtGM7ng06rrGDceONOQh0PHMZ4',
    appId: '1:615185650546:web:5914d0aee5e2d69ab0c3eb',
    messagingSenderId: '615185650546',
    projectId: 'chatly-5bc63',
    authDomain: 'chatly-5bc63.firebaseapp.com',
    storageBucket: 'chatly-5bc63.firebasestorage.app',
  );
}
